import type { Metadata } from "next";
import "./globals.css";
import { Footer, Header } from "@/components/index";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Header />
        <div className="min-h-[90vh] px-4">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
